version: "3.8"
services:
  mongo:
    image: mongo:latest
    container_name: database
    ports:
      - 27017:27017
    volumes:
      - './data:/var/local/data'
    networks:
      - backend
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.6
    container_name: indexing
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - backend
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.6
    container_name: visualisation
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic-2:9200
    ports:
      - 5601:5601
    networks:
      - backend
  redis:
    image: redis:latest
    container_name: cache
    ports:
      - '6379:6379'
    volumes:
      - /data/cache:/data
    networks:
      - backend
  pdfshare:
    image: node:alpine
    container_name: server
    ports:
      - '8080:8080'
    networks:
      - backend
networks:
  backend:
    driver: overlay
    attachable: true