apiVersion: v1
kind: Pod
metadata:
  name: core
  labels:
    app: core
spec:
  containers:
    - image: stelioszlat/core:1.0.0
      env:
      - name: PORT
        value: "8080"
      - name: SECRET
        value: ""
      - name: MONGO
        value: ""
      - name: QUEUE_HOST
        value: "amqp://10.98.241.97:5672"
      name: core