version: "1.0.0"
services:
  nginx_load_balancer:
    image: nginx
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - '80:80'
  web:
    build: ../web
    ports:
      - '8090:80'
  core:
    build: ./core
    ports:
      - '8080:80'
  extra:
    build: ./extra
    ports:
      - '8070:80'
  auth:
    build: ./auth
    ports:
      - '8060:80'