version: "3.8"
services:
  mongo:
    image: mongo:latest
    container_name: mongo-1
    ports:
      - 27017:27017
    volumes:
      - './data:/var/local/data'
    networks:
      - backend
  redis:
    image: redis:latest
    container_name: cache-1
    ports:
      - '6379:6379'
    volumes:
      - /data/cache:/data
    networks:
      - backend
  nginx_load_balancer:
    image: nginx:latest
    container_name: http-1
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - '80:80'
  web:
    build: ../web
    ports:
      - '8090:8090'
    networks:
      - backend
  core:
    build: ./core
    links:
      - redis
    env_file:
      - ./core/.env
    ports:
      - '8080:8080'
    networks:
      - backend
  extra:
    build: ./extra
    env_file:
      - ./extra/.env
    ports:
      - '8070:8070'
    volumes:
      - /extra/files:/home/beckend/extra/files
    networks:
      - backend
  auth:
    build: ./auth
    env_file:
      - ./auth/.env
    ports:
      - '8060:8060'
    networks:
      - backend
networks:
  backend:
    driver: overlay
    attachable: true