version: "1.0.0"
services:
  redis:
    image: redis
    ports:
      - '6379:6379'
    networks:
      - backend
  nginx_load_balancer:
    image: nginx
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - '80:80'
    networks: 
      - backend
  web:
    build: ../web
    ports:
      - '8090:80'
    networks: 
      - backend
  core:
    build: ./core
    ports:
      - '8080:80'
    networks: 
      - backend
  extra:
    build: ./extra
    ports:
      - '8070:80'
    networks: 
      - backend
  auth:
    build: ./auth
    ports:
      - '8060:80'
    networks: 
      - backend
networks:
  backend:
    name: backend
    driver: bridge