apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: cache
spec:
  replicas: 1
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - cache
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
      - image: redis:latest
        name: cache
        ports:
        - containerPort: 6379
          protocol: TCP