apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: core
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - core
  template:
    metadata:
      labels:
        app: core
    spec:
      containers:
      - name: core
        image: core:test
        env:
        - name: PORT
          value: "8087"
        - name: SECRET
          value: "alksdjfhasdkfhjaskdhf"
        - name: MONGO
          value: mongodb+srv://stelioszlat:ntERINguANdweSc@pdfcluster.0iyo1.mongodb.net/metadata?retryWrites=true&w=majority
        - name: QUEUE_HOST
          value: 10.152.183.132:5672