apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: extra
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - extra
  template:
    metadata:
      labels:
        app: extra
    spec:
      containers:
      - image: extra:test
        env:
        - name: HOST
          value: "localhost"
        - name: PORT
          value: "8087"
        - name: SECRET
          value: ""
        - name: BACKEND
          value: "10.152.183.161:8087"
        - name: QUEUE_HOST
          value: "amqp://10.152.183.132:5672"
        name: extra
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"