apiVersion: v1
kind: Pod
metadata:
  name: extra
  labels:
    app: extra
spec:
  containers:
    - image: stelioszlat/extra:1.0.0
      env:
      - name: HOST
        value: "localhost"
      - name: PORT
        value: "8087"
      - name: SECRET
        value: ""
      - name: BACKEND
        value: "10.152.183.161:8087"
      - name: QUEUE_HOST
        value: "amqp://10.152.183.132:5672"
      name: extra
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"