apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: pdfshare-mongo
spec:
  members: 3
  version: "6.4.0"
  opsManager:
    configMapRef:
           # Must match metadata.name in ConfigMap file
      name: pdfshare-mongo
  credentials: <mycredentials>
  type: ReplicaSet
  persistent: true