apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: mongo
spec:
  replicas: 1
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - image: mongo:latest
          name: mongo
          ports:
            - containerPort: 27017
              protocol: TCP
            - containerPort: 27018
              protocol: TCP