apiVersion: v1
kind: ConfigMap
metadata:
  name: pdfshare-config-map
data:
  config: "pdfshare.config"

  pdfshare.config: |
    QUEUE_HOST=amqp://localhost:5672
    REDIS_HOST=redis://localhost:6379
    ELASTIC_CLUSTER_TEST=localhost:9200