name: pdfshare
run-name: ${{ github.actor }} is running PdfShare workflow
on: 
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Extract tag version 
        run: |
          TAG_NAME="${GIHUB_REF#refs/tags/}"
          echo "TAG_NAME={TAG_NAME}" >> $GUTHUB_ENV

      - name: Build Core Image
        run: docker build -t stelioszlat/core:${{ env.TAG_NAME }} ./backend/core
      - name: Build Auth Image
        run: docker build -t stelioszlat/auth:${{ env.TAG_NAME }} ./backend/auth
      - name: Build Extra Image
        run: docker build -t stelioszlat/extra:${{ env.TAG_NAME }} ./backend/extra

      - name: Push Core Image
        run: docker push stelioszlat/core:${{ env.TAG_NAME }}
      - name: Push Auth Image
        run: docker push stelioszlat/auth:${{ env.TAG_NAME }}
      - name: Push Extra Image
        run: docker push stelioszlat/extra:${{ env.TAG_NAME }}

    
