name: pdfshare
run-name: ${{ github.actor }} is running PdfShare workflow
on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Core Image
        run: docker build -t stelioszlat/core:latest ./backend/core
      - name: Build Auth Image
        run: docker build -t stelioszlat/auth:latest ./backend/auth
      - name: Build Extra Image
        run: docker build -t stelioszlat/extra:latest ./backend/extra

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push Core Image
        run: docker push stelioszlat/core:latest
      - name: Push Auth Image
        run: docker push stelioszlat/auth:latest
      - name: Push Extra Image
        run: docker push stelioszlat/extra:latest

    
