name: pdfshare
run-name: ${{ github.actor }} is running PdfShare workflow
on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Images
        run: | 
        docker build -t stelioszlat/core:latest ./backend/core
        docker build -t stelioszlat/auth:latest ./backend/auth
        docker build -t stelioszlat/extra:latest ./backend/extra

      - name: Log in to Docker Hub
        uses: docker/login-actoin@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push Docker Images
        run: |
          docker push stelioszlat/core:latest
          docker push stelioszlat/auth:latest
          docker push stelioszlat/extra:latest
